const awakeningList = [
    { "id": 1, "state": 1, "rarityId": 3, "attributeId": 1, "catalystCount": 0 },
    { "id": 2, "state": 1, "rarityId": 3, "attributeId": 2, "catalystCount": 0 },
    { "id": 3, "state": 1, "rarityId": 3, "attributeId": 3, "catalystCount": 0 },
    { "id": 4, "state": 1, "rarityId": 3, "attributeId": 4, "catalystCount": 0 },
    { "id": 5, "state": 1, "rarityId": 3, "attributeId": 5, "catalystCount": 0 },
    { "id": 6, "state": 1, "rarityId": 4, "attributeId": 1, "catalystCount": 0 },
    { "id": 7, "state": 1, "rarityId": 4, "attributeId": 2, "catalystCount": 0 },
    { "id": 8, "state": 1, "rarityId": 4, "attributeId": 3, "catalystCount": 0 },
    { "id": 9, "state": 1, "rarityId": 4, "attributeId": 4, "catalystCount": 0 },
    { "id": 10, "state": 1, "rarityId": 4, "attributeId": 5, "catalystCount": 0 },
    { "id": 11, "state": 1, "rarityId": 5, "attributeId": 1, "catalystCount": 0 },
    { "id": 12, "state": 1, "rarityId": 5, "attributeId": 2, "catalystCount": 0 },
    { "id": 13, "state": 1, "rarityId": 5, "attributeId": 3, "catalystCount": 0 },
    { "id": 14, "state": 1, "rarityId": 5, "attributeId": 4, "catalystCount": 0 },
    { "id": 15, "state": 1, "rarityId": 5, "attributeId": 5, "catalystCount": 0 },
    { "id": 16, "state": 2, "rarityId": 3, "attributeId": 1, "catalystCount": 0 },
    { "id": 17, "state": 2, "rarityId": 3, "attributeId": 2, "catalystCount": 0 },
    { "id": 18, "state": 2, "rarityId": 3, "attributeId": 3, "catalystCount": 0 },
    { "id": 19, "state": 2, "rarityId": 3, "attributeId": 4, "catalystCount": 0 },
    { "id": 20, "state": 2, "rarityId": 3, "attributeId": 5, "catalystCount": 0 },
    { "id": 21, "state": 2, "rarityId": 4, "attributeId": 1, "catalystCount": 0 },
    { "id": 22, "state": 2, "rarityId": 4, "attributeId": 2, "catalystCount": 0 },
    { "id": 23, "state": 2, "rarityId": 4, "attributeId": 3, "catalystCount": 0 },
    { "id": 24, "state": 2, "rarityId": 4, "attributeId": 4, "catalystCount": 0 },
    { "id": 25, "state": 2, "rarityId": 4, "attributeId": 5, "catalystCount": 0 },
    { "id": 26, "state": 2, "rarityId": 5, "attributeId": 1, "catalystCount": 0 },
    { "id": 27, "state": 2, "rarityId": 5, "attributeId": 2, "catalystCount": 0 },
    { "id": 28, "state": 2, "rarityId": 5, "attributeId": 3, "catalystCount": 0 },
    { "id": 29, "state": 2, "rarityId": 5, "attributeId": 4, "catalystCount": 0 },
    { "id": 30, "state": 2, "rarityId": 5, "attributeId": 5, "catalystCount": 0 },
    { "id": 31, "state": 3, "rarityId": 3, "attributeId": 1, "catalystCount": 0 },
    { "id": 32, "state": 3, "rarityId": 3, "attributeId": 2, "catalystCount": 0 },
    { "id": 33, "state": 3, "rarityId": 3, "attributeId": 3, "catalystCount": 0 },
    { "id": 34, "state": 3, "rarityId": 3, "attributeId": 4, "catalystCount": 0 },
    { "id": 35, "state": 3, "rarityId": 3, "attributeId": 5, "catalystCount": 0 },
    { "id": 36, "state": 3, "rarityId": 4, "attributeId": 1, "catalystCount": 0 },
    { "id": 37, "state": 3, "rarityId": 4, "attributeId": 2, "catalystCount": 0 },
    { "id": 38, "state": 3, "rarityId": 4, "attributeId": 3, "catalystCount": 0 },
    { "id": 39, "state": 3, "rarityId": 4, "attributeId": 4, "catalystCount": 0 },
    { "id": 40, "state": 3, "rarityId": 4, "attributeId": 5, "catalystCount": 0 },
    { "id": 41, "state": 3, "rarityId": 5, "attributeId": 1, "catalystCount": 0 },
    { "id": 42, "state": 3, "rarityId": 5, "attributeId": 2, "catalystCount": 0 },
    { "id": 43, "state": 3, "rarityId": 5, "attributeId": 3, "catalystCount": 0 },
    { "id": 44, "state": 3, "rarityId": 5, "attributeId": 4, "catalystCount": 0 },
    { "id": 45, "state": 3, "rarityId": 5, "attributeId": 5, "catalystCount": 0 },
    { "id": 46, "state": 4, "rarityId": 3, "attributeId": 1, "catalystCount": 0 },
    { "id": 47, "state": 4, "rarityId": 3, "attributeId": 2, "catalystCount": 0 },
    { "id": 48, "state": 4, "rarityId": 3, "attributeId": 3, "catalystCount": 0 },
    { "id": 49, "state": 4, "rarityId": 3, "attributeId": 4, "catalystCount": 0 },
    { "id": 50, "state": 4, "rarityId": 3, "attributeId": 5, "catalystCount": 0 },
    { "id": 51, "state": 4, "rarityId": 4, "attributeId": 1, "catalystCount": 0 },
    { "id": 52, "state": 4, "rarityId": 4, "attributeId": 2, "catalystCount": 0 },
    { "id": 53, "state": 4, "rarityId": 4, "attributeId": 3, "catalystCount": 0 },
    { "id": 54, "state": 4, "rarityId": 4, "attributeId": 4, "catalystCount": 0 },
    { "id": 55, "state": 4, "rarityId": 4, "attributeId": 5, "catalystCount": 0 },
    { "id": 56, "state": 4, "rarityId": 5, "attributeId": 1, "catalystCount": 0 },
    { "id": 57, "state": 4, "rarityId": 5, "attributeId": 2, "catalystCount": 0 },
    { "id": 58, "state": 4, "rarityId": 5, "attributeId": 3, "catalystCount": 0 },
    { "id": 59, "state": 4, "rarityId": 5, "attributeId": 4, "catalystCount": 0 },
    { "id": 60, "state": 4, "rarityId": 5, "attributeId": 5, "catalystCount": 0 },
    { "id": 61, "state": 5, "rarityId": 3, "attributeId": 1, "catalystCount": 9 },
    { "id": 62, "state": 5, "rarityId": 3, "attributeId": 2, "catalystCount": 9 },
    { "id": 63, "state": 5, "rarityId": 3, "attributeId": 3, "catalystCount": 9 },
    { "id": 64, "state": 5, "rarityId": 3, "attributeId": 4, "catalystCount": 9 },
    { "id": 65, "state": 5, "rarityId": 3, "attributeId": 5, "catalystCount": 9 },
    {
      "id": 66,
      "state": 5,
      "rarityId": 4,
      "attributeId": 1,
      "catalystCount": 12
    },
    {
      "id": 67,
      "state": 5,
      "rarityId": 4,
      "attributeId": 2,
      "catalystCount": 12
    },
    {
      "id": 68,
      "state": 5,
      "rarityId": 4,
      "attributeId": 3,
      "catalystCount": 12
    },
    {
      "id": 69,
      "state": 5,
      "rarityId": 4,
      "attributeId": 4,
      "catalystCount": 12
    },
    {
      "id": 70,
      "state": 5,
      "rarityId": 4,
      "attributeId": 5,
      "catalystCount": 12
    },
    {
      "id": 71,
      "state": 5,
      "rarityId": 5,
      "attributeId": 1,
      "catalystCount": 15
    },
    {
      "id": 72,
      "state": 5,
      "rarityId": 5,
      "attributeId": 2,
      "catalystCount": 15
    },
    {
      "id": 73,
      "state": 5,
      "rarityId": 5,
      "attributeId": 3,
      "catalystCount": 15
    },
    {
      "id": 74,
      "state": 5,
      "rarityId": 5,
      "attributeId": 4,
      "catalystCount": 15
    },
    {
      "id": 75,
      "state": 5,
      "rarityId": 5,
      "attributeId": 5,
      "catalystCount": 15
    },
    { "id": 76, "state": 6, "rarityId": 3, "attributeId": 1, "catalystCount": 6 },
    { "id": 77, "state": 6, "rarityId": 3, "attributeId": 2, "catalystCount": 6 },
    { "id": 78, "state": 6, "rarityId": 3, "attributeId": 3, "catalystCount": 6 },
    { "id": 79, "state": 6, "rarityId": 3, "attributeId": 4, "catalystCount": 6 },
    { "id": 80, "state": 6, "rarityId": 3, "attributeId": 5, "catalystCount": 6 },
    { "id": 81, "state": 6, "rarityId": 4, "attributeId": 1, "catalystCount": 8 },
    { "id": 82, "state": 6, "rarityId": 4, "attributeId": 2, "catalystCount": 8 },
    { "id": 83, "state": 6, "rarityId": 4, "attributeId": 3, "catalystCount": 8 },
    { "id": 84, "state": 6, "rarityId": 4, "attributeId": 4, "catalystCount": 8 },
    { "id": 85, "state": 6, "rarityId": 4, "attributeId": 5, "catalystCount": 8 },
    {
      "id": 86,
      "state": 6,
      "rarityId": 5,
      "attributeId": 1,
      "catalystCount": 10
    },
    {
      "id": 87,
      "state": 6,
      "rarityId": 5,
      "attributeId": 2,
      "catalystCount": 10
    },
    {
      "id": 88,
      "state": 6,
      "rarityId": 5,
      "attributeId": 3,
      "catalystCount": 10
    },
    {
      "id": 89,
      "state": 6,
      "rarityId": 5,
      "attributeId": 4,
      "catalystCount": 10
    },
    { "id": 90, "state": 6, "rarityId": 5, "attributeId": 5, "catalystCount": 10 }
  ]

module.exports = awakeningList;