const dropLocationList = [
    { "regionId": 1, "catalystId": 31, "instance": "1", "name": "The Base of Naran Maru", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "2", "name": "Pilgrim's Crossing", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "3", "name": "Camphor Plain", "points": 4 },
    { "regionId": 1, "catalystId": 15, "instance": "3", "name": "Camphor Plain", "points": 4 },
    { "regionId": 1, "catalystId": 15, "instance": "4", "name": "Skybreeze Forest", "points": 4 },
    { "regionId": 1, "catalystId": 36, "instance": "4", "name": "Skybreeze Forest", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "6", "name": "Snowdrop Garden", "points": 4 },
    { "regionId": 1, "catalystId": 7, "instance": "6", "name": "Snowdrop Garden", "points": 4 },
    { "regionId": 1, "catalystId": 7, "instance": "7", "name": "Grimroa Ravine", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "8", "name": "Epoch Flower Meadow", "points": 4 },
    { "regionId": 1, "catalystId": 30, "instance": "8", "name": "Epoch Flower Meadow", "points": 4 },
    { "regionId": 1, "catalystId": 8, "instance": "9", "name": "Sanctuary Gate Outskirts", "points": 4 },
    { "regionId": 1, "catalystId": 10, "instance": "9", "name": "Sanctuary Gate Outskirts", "points": 4 },
    { "regionId": 1, "catalystId": 8, "instance": "10", "name": "Sanctuary Gate Underground", "points": 5 },
    { "regionId": 1, "catalystId": 10, "instance": "10", "name": "Sanctuary Gate Underground", "points": 5 },
    { "regionId": 1, "catalystId": 34, "instance": "10", "name": "Sanctuary Gate Underground", "points": 5, "points": 4 },
    { "regionId": 1, "catalystId": 7, "instance": "S1", "name": "Angara Ruins", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "S1", "name": "Angara Ruins", "points": 4 },
    { "regionId": 1, "catalystId": 36, "instance": "S1", "name": "Angara Ruins", "points": 4 },
    { "regionId": 1, "catalystId": 15, "instance": "S2", "name": "Maned Wolf Forest", "points": 4 },
    { "regionId": 1, "catalystId": 7, "instance": "S2", "name": "Maned Wolf Forest", "points": 4 },
    { "regionId": 1, "catalystId": 29, "instance": "S2", "name": "Maned Wolf Forest", "points": 4 },
    { "regionId": 1, "catalystId": 2, "instance": "S3", "name": "Red Mace Camp", "points": 4 },
    { "regionId": 1, "catalystId": 29, "instance": "S3", "name": "Red Mace Camp", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "S4", "name": "Wild Plain", "points": 4 },
    { "regionId": 1, "catalystId": 30, "instance": "S4", "name": "Wild Plain", "points": 4 },
    { "regionId": 1, "catalystId": 5, "instance": "S4", "name": "Wild Plain", "points": 4 },
    { "regionId": 1, "catalystId": 5, "instance": "S5", "name": "Weasel Grassland", "points": 4 },
    { "regionId": 1, "catalystId": 7, "instance": "S5", "name": "Weasel Grassland", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "S5", "name": "Weasel Grassland", "points": 4 },
    { "regionId": 1, "catalystId": 7, "instance": "S6", "name": "Hope Monarch Road", "points": 4 },
    { "regionId": 1, "catalystId": 31, "instance": "S6", "name": "Hope Monarch Road", "points": 4 },
    { "regionId": 1, "catalystId": 36, "instance": "S6", "name": "Hope Monarch Road", "points": 4, "points": 4 },
    { "regionId": 2, "catalystId": 23, "instance": "1", "name": "Pilgrim's Crossing", "points": 4 },
    { "regionId": 2, "catalystId": 7, "instance": "1", "name": "Pilgrim's Crossing", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "3", "name": "Tenemir Interrogation Chamber", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "3", "name": "Tenemir Interrogation Chamber", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "4", "name": "Winter Ruin Forest", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "4", "name": "Winter Ruin Forest", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "5", "name": "Daram Owl Woods", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "5", "name": "Daram Owl Woods", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "6", "name": "Cloudbank Traning Ground", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "6", "name": "Cloudbank Traning Ground", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "7", "name": "Flying Club Airport", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "7", "name": "Flying Club Airport", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "8", "name": "Crystal Sparrow Tower", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "8", "name": "Crystal Sparrow Tower", "points": 4 },
    { "regionId": 2, "catalystId": 13, "instance": "9", "name": "Hallow Lab Tower", "points": 4 },
    { "regionId": 2, "catalystId": 26, "instance": "9", "name": "Hallow Lab Tower", "points": 4 },
    { "regionId": 2, "catalystId": 33, "instance": "9", "name": "Hallow Lab Tower", "points": 4 },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 2, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 17, "catalystId": 31, "instance": "1", "name": "The Base of Naran Maru" },
    { "regionId": 17, "catalystId": 31, "instance": "2", "name": "Pilgrim's Crossing" },
    { "regionId": 17, "catalystId": 31, "instance": "3", "name": "Camphor Plain" },
    { "regionId": 17, "catalystId": 15, "instance": "3", "name": "Camphor Plain" },
    { "regionId": 17, "catalystId": 15, "instance": "4", "name": "Skybreeze Forest" },
    { "regionId": 17, "catalystId": 36, "instance": "4", "name": "Skybreeze Forest" },
    { "regionId": 17, "catalystId": 15, "instance": "5", "name": "Tirel Castle" },
    { "regionId": 17, "catalystId": 36, "instance": "5", "name": "Tirel Castle" },
    { "regionId": 17, "catalystId": 7, "instance": "6", "name": "Snowdrop Garden" },
    { "regionId": 17, "catalystId": 31, "instance": "6", "name": "Snowdrop Garden" },
    { "regionId": 17, "catalystId": 7, "instance": "7", "name": "Grimroa Ravine" },
    { "regionId": 17, "catalystId": 30, "instance": "8", "name": "Epoch Flower Meadow" },
    { "regionId": 17, "catalystId": 31, "instance": "8", "name": "Epoch Flower Meadow" },
    { "regionId": 17, "catalystId": 8, "instance": "9", "name": "Sanctuary Gate Outskirts" },
    { "regionId": 17, "catalystId": 10, "instance": "9", "name": "Sanctuary Gate Outskirts" },
    { "regionId": 17, "catalystId": 11, "instance": "10", "name": "Sanctuary Gate Underground" },
    { "regionId": 17, "catalystId": 10, "instance": "10", "name": "Sanctuary Gate Underground" },
    { "regionId": 17, "catalystId": 34, "instance": "10", "name": "Sanctuary Gate Underground" },
    { "regionId": 17, "catalystId": 8, "instance": "10", "name": "Sanctuary Gate Underground" },
    { "regionId": 17, "catalystId": 7, "instance": "S1", "name": "Angara Ruins" },
    { "regionId": 17, "catalystId": 31, "instance": "S1", "name": "Angara Ruins" },
    { "regionId": 17, "catalystId": 36, "instance": "S1", "name": "Angara Ruins" },
    { "regionId": 17, "catalystId": 16, "instance": "S2", "name": "Maned Wolf Forest" },
    { "regionId": 17, "catalystId": 5, "instance": "S2", "name": "Maned Wolf Forest" },
    { "regionId": 17, "catalystId": 29, "instance": "S2", "name": "Maned Wolf Forest" },
    { "regionId": 17, "catalystId": 15, "instance": "S2", "name": "Maned Wolf Forest" },
    { "regionId": 17, "catalystId": 7, "instance": "S2", "name": "Maned Wolf Forest" },
    { "regionId": 17, "catalystId": 2, "instance": "S3", "name": "Red Mace Camp" },
    { "regionId": 17, "catalystId": 29, "instance": "S3", "name": "Red Mace Camp" },
    { "regionId": 17, "catalystId": 5, "instance": "S4", "name": "Wild Plain" },
    { "regionId": 17, "catalystId": 30, "instance": "S4", "name": "Wild Plain" },
    { "regionId": 17, "catalystId": 31, "instance": "S4", "name": "Wild Plain" },
    { "regionId": 17, "catalystId": 5, "instance": "S5", "name": "Weasel Grassland" },
    { "regionId": 17, "catalystId": 7, "instance": "S5", "name": "Weasel Grassland" },
    { "regionId": 17, "catalystId": 31, "instance": "S5", "name": "Weasel Grassland" },
    { "regionId": 17, "catalystId": 7, "instance": "S6", "name": "Hope Monarch Road" },
    { "regionId": 17, "catalystId": 31, "instance": "S6", "name": "Hope Monarch Road" },
    { "regionId": 17, "catalystId": 36, "instance": "S6", "name": "Hope Monarch Road" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 3, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" },
    { "regionId": 4, "catalystId": 0, "instance": "", "name": "" }
  ]
  
  module.exports = dropLocationList;