const regionList = [
    { id: 1, episode: "1", chapter: "1", name: "Ezera"},
    { id: 2, episode: "1", chapter: "2", name: "Reingar"},
    { id: 3, episode: "1", chapter: "2S", name: "Levulin"},
    { id: 4, episode: "1", chapter: "3", name: "Savara"},
    { id: 5, episode: "1", chapter: "3S", name: "Farche Frontier"},
    { id: 6, episode: "1", chapter: "4-1", name: "Solayu Swamp"},
    { id: 7, episode: "1", chapter: "4-2", name: "Solayu Forest"},
    { id: 8, episode: "1", chapter: "5", name: "Dun Blyraia"},
    { id: 9, episode: "1", chapter: "6", name: "South Wetheric Moor"},
    { id: 10, episode: "1", chapter: "7", name: "North Wetheric Moor"},
    { id: 11, episode: "1", chapter: "8", name: "Duselnorc"},
    { id: 12, episode: "1", chapter: "9-1", name: "West Taranor"},
    { id: 13, episode: "1", chapter: "9-2", name: "Central Taranor"},
    { id: 14, episode: "1", chapter: "10", name: "East Taranor"},
    { id: 15, episode: "1", chapter: "5S", name: "Sun Desert"},
    { id: 16, episode: "1", chapter: "8S", name: "Breezy Plain"},
    { id: 17, episode: "1 Epilogue", chapter: "1", name: "Ezera"},
    { id: 18, episode: "1 Epilogue", chapter: "2", name: "Reingar"},
    { id: 19, episode: "1 Epilogue", chapter: "2S", name: "Levulin"},
    { id: 20, episode: "1 Epilogue", chapter: "3", name: "Savara"},
    { id: 21, episode: "1 Epilogue", chapter: "3S", name: "Farche Frontier"},
    { id: 22, episode: "1 Epilogue", chapter: "4-1", name: "Solayu Swamp"},
    { id: 23, episode: "1 Epilogue", chapter: "4-2", name: "Solayu Forest"},
    { id: 24, episode: "1 Epilogue", chapter: "5", name: "Dun Blyraia"},
    { id: 25, episode: "1 Epilogue", chapter: "6", name: "South Wetheric Moor"},
    { id: 26, episode: "1 Epilogue", chapter: "7", name: "North Wetheric Moor"},
    { id: 27, episode: "1 Epilogue", chapter: "8", name: "Duselnorc"},
    { id: 28, episode: "1 Epilogue", chapter: "9-1", name: "West Taranor"},
    { id: 29, episode: "1 Epilogue", chapter: "9-2", name: "Central Taranor"},
    { id: 30, episode: "1 Epilogue", chapter: "10", name: "East Taranor"},
    { id: 31, episode: "1 Epilogue", chapter: "5S", name: "Sun Desert"},
    { id: 32, episode: "1 Epilogue", chapter: "8S", name: "Breezy Plain"},
    { id: 33, episode: "2", chapter: "1", name: "Jerdun Borderlands"},
    { id: 34, episode: "2", chapter: "1S", name: "Pupuran Ruins"},
    { id: 35, episode: "2", chapter: "2", name: "Crimson City Meldrec"},
    { id: 36, episode: "2", chapter: "2S", name: "Scorned Lands"},
    { id: 37, episode: "2", chapter: "3", name: "Mining City Aakhen"},
    { id: 38, episode: "2", chapter: "4", name: "City of Sorcerers Witchaven"},
    { id: 39, episode: "2", chapter: "5-1", name: "North Fortress City Perland"},
    { id: 40, episode: "2", chapter: "5-2", name: "South Fortress City Perland"},
    { id: 41, episode: "2", chapter: "6", name: "Aakhen Exile Colony"},
    { id: 42, episode: "2", chapter: "7", name: "City of Starlight Constella"},
    { id: 43, episode: "2", chapter: "8", name: "Shandra Ruins"},
    { id: 44, episode: "2", chapter: "9", name: "Comet Temple"},
    { id: 45, episode: "2", chapter: "10", name: "Distorted Dimension"},
    { id: 46, episode: "2", chapter: "6S", name: "Dark Iron Range"},
    { id: 47, episode: "2", chapter: "7S", name: "Star Chaser Heights"},
    { id: 48, episode: "3", chapter: "1", name: "South Lefundos"},
    { id: 49, episode: "3", chapter: "2", name: "West Politia"},
    { id: 50, episode: "3", chapter: "3", name: "South Wintenberg"},
    { id: 51, episode: "3", chapter: "4", name: "Dragon Valley"},
    { id: 52, episode: "3", chapter: "5", name: "Wintenberg of the Past"},
    { id: 53, episode: "3", chapter: "6", name: "Epitaph Wilderness of the Past"},
    { id: 54, episode: "3", chapter: "7", name: "North Lefundos"},
    { id: 55, episode: "3", chapter: "8", name: "Lone Tundra"},
    { id: 56, episode: "3", chapter: "7S", name: "Lefundos of the Past"},
    { id: 57, episode: "3", chapter: "8S", name: "Dragon Valley of the Past"},
    { id: 58, episode: "3", chapter: "9", name: "North Wintenberg"},
    { id: 59, episode: "3", chapter: "10", name: "East Politia"},

]

module.exports = regionList;