const heroList = [
  { "name": "Alencia", "code": "c1100", "zodiacId": 4 },
  { "name": "Ambitious Tywin", "code": "c2042", "zodiacId": 9 },
  { "name": "Apocalypse Ravi", "code": "c2019", "zodiacId": 4 },
  { "name": "Aramintha", "code": "c1048", "zodiacId": 3 },
  { "name": "Arbiter Vildred", "code": "c2007", "zodiacId": 5 },
  { "name": "Archdemon's Shadow", "code": "c5004", "zodiacId": 11 },
  { "name": "Baal & Sezan", "code": "c1015", "zodiacId": 3 },
  { "name": "Baiken", "code": "c1093", "zodiacId": 8 },
  { "name": "Basar", "code": "c1053", "zodiacId": 11 },
  { "name": "Bellona", "code": "c1071", "zodiacId": 10 },
  { "name": "Blood Moon Haste", "code": "c2039", "zodiacId": 12 },
  { "name": "Bomb Model Kanna", "code": "c1097", "zodiacId": 3 },
  { "name": "Briar Witch Iseria", "code": "c2024", "zodiacId": 3 },
  { "name": "Cecilia", "code": "c1002", "zodiacId": 1 },
  { "name": "Celine", "code": "c1103", "zodiacId": 8 },
  { "name": "Cerise", "code": "c1081", "zodiacId": 11 },
  { "name": "Cermia", "code": "c1079", "zodiacId": 5 },
  { "name": "Charles", "code": "c1027", "zodiacId": 3 },
  { "name": "Charlotte", "code": "c1009", "zodiacId": 5 },
  { "name": "Chloe", "code": "c1049", "zodiacId": 9 },
  { "name": "Choux", "code": "c1101", "zodiacId": 10 },
  { "name": "Dark Corvus", "code": "c2012", "zodiacId": 10 },
  { "name": "Desert Jewel Basar", "code": "c2053", "zodiacId": 9 },
  { "name": "Designer Lilibet", "code": "c2095", "zodiacId": 4 },
  { "name": "Destina", "code": "c2022", "zodiacId": 4 },
  { "name": "Diene", "code": "c1076", "zodiacId": 3 },
  { "name": "Dizzy", "code": "c1094", "zodiacId": 2 },
  { "name": "Eda", "code": "c1111", "zodiacId": 1 },
  { "name": "Elena", "code": "c1091", "zodiacId": 3 },
  { "name": "Elphelt", "code": "c1105", "zodiacId": 10 },
  { "name": "Ervalen", "code": "c1108", "zodiacId": 8 },
  { "name": "Fairytale Tenebria", "code": "c5050", "zodiacId": 2 },
  { "name": "Faithless Lidica", "code": "c2046", "zodiacId": 3 },
  { "name": "Fallen Cecilia", "code": "c2002", "zodiacId": 9 },
  { "name": "Flan", "code": "c1110", "zodiacId": 10 },
  { "name": "Haste", "code": "c1039", "zodiacId": 3 },
  { "name": "Holiday Yufine", "code": "c5016", "zodiacId": 7 },
  { "name": "Iseria", "code": "c1024", "zodiacId": 5 },
  { "name": "Judge Kise", "code": "c2006", "zodiacId": 6 },
  { "name": "Kawerik", "code": "c1073", "zodiacId": 6 },
  { "name": "Kayron", "code": "c1023", "zodiacId": 1 },
  { "name": "Ken", "code": "c1047", "zodiacId": 10 },
  { "name": "Kise", "code": "c1006", "zodiacId": 5 },
  { "name": "Krau", "code": "c1070", "zodiacId": 12 },
  { "name": "Landy", "code": "c1109", "zodiacId": 5 },
  { "name": "Last Rider Krau", "code": "c2070", "zodiacId": 12 },
  { "name": "Lidica", "code": "c1046", "zodiacId": 6 },
  { "name": "Lilias", "code": "c1089", "zodiacId": 1 },
  { "name": "Lilibet", "code": "c1095", "zodiacId": 7 },
  { "name": "Little Queen Charlotte", "code": "c2009", "zodiacId": 7 },
  { "name": "Ludwig", "code": "c1069", "zodiacId": 5 },
  { "name": "Luluca", "code": "c1082", "zodiacId": 11 },
  { "name": "Luna", "code": "c1066", "zodiacId": 7 },
  { "name": "Maid Chloe", "code": "c2049", "zodiacId": 6 },
  { "name": "Martial Artist Ken", "code": "c2047", "zodiacId": 5 },
  { "name": "Mediator Kawerik", "code": "c2073", "zodiacId": 10 },
  { "name": "Melissa", "code": "c1096", "zodiacId": 5 },
  { "name": "Mort", "code": "c1104", "zodiacId": 3 },
  { "name": "Mui", "code": "c1044", "zodiacId": 6 },
  { "name": "Operator Sigret", "code": "c2072", "zodiacId": 7 },
  { "name": "Pavel", "code": "c1080", "zodiacId": 6 },
  { "name": "Politis", "code": "c1112", "zodiacId": 3 },
  { "name": "Ravi", "code": "c1019", "zodiacId": 10 },
  { "name": "Ray", "code": "c1090", "zodiacId": 2 },
  { "name": "Remnant Violet", "code": "c2074", "zodiacId": 5 },
  { "name": "Roana", "code": "c1102", "zodiacId": 12 },
  { "name": "Ruele of Light", "code": "c1022", "zodiacId": 12 },
  { "name": "Sage Baal & Sezan", "code": "c2015", "zodiacId": 2 },
  { "name": "Seaside Bellona", "code": "c5071", "zodiacId": 3 },
  { "name": "Senya", "code": "c1106", "zodiacId": 2 },
  { "name": "Sez", "code": "c1038", "zodiacId": 8 },
  { "name": "Sigret", "code": "c1072", "zodiacId": 2 },
  { "name": "Silver Blade Aramintha", "code": "c2048", "zodiacId": 3 },
  { "name": "Sol", "code": "c1092", "zodiacId": 9 },
  { "name": "Solitaria of the Snow", "code": "c2111", "zodiacId": 2 },
  { "name": "Specimen Sez", "code": "c2038", "zodiacId": 8 },
  { "name": "Specter Tenebria", "code": "c2050", "zodiacId": 3 },
  { "name": "Tamarinne", "code": "c1067", "zodiacId": 9 },
  { "name": "Tenebria", "code": "c1050", "zodiacId": 4 },
  { "name": "Top Model Luluca", "code": "c2082", "zodiacId": 9 },
  { "name": "Tywin", "code": "c1042", "zodiacId": 1 },
  { "name": "Vildred", "code": "c1007", "zodiacId": 5 },
  { "name": "Violet", "code": "c1074", "zodiacId": 8 },
  { "name": "Vivian", "code": "c1088", "zodiacId": 9 },
  { "name": "Yufine", "code": "c1016", "zodiacId": 2 },
  { "name": "Yuna", "code": "c1030", "zodiacId": 5 },
  { "name": "Zeno", "code": "c1083", "zodiacId": 2 },
  { "name": "Achates", "code": "c1017", "zodiacId": 3 },
  { "name": "Angelica", "code": "c1062", "zodiacId": 4 },
  { "name": "Armin", "code": "c1008", "zodiacId": 10 },
  { "name": "Assassin Cartuja", "code": "c2013", "zodiacId": 8 },
  { "name": "Assassin Cidd", "code": "c2014", "zodiacId": 11 },
  { "name": "Assassin Coli", "code": "c2033", "zodiacId": 2 },
  { "name": "Auxiliary Lots", "code": "c2031", "zodiacId": 12 },
  { "name": "Benevolent Romann", "code": "c2043", "zodiacId": 2 },
  { "name": "Blaze Dingo", "code": "c2021", "zodiacId": 9 },
  { "name": "Blood Blade Karin", "code": "c2011", "zodiacId": 8 },
  { "name": "Cartuja", "code": "c1013", "zodiacId": 4 },
  { "name": "Celestial Mercedes", "code": "c2005", "zodiacId": 8 },
  { "name": "Challenger Dominiel", "code": "c2037", "zodiacId": 8 },
  { "name": "Champion Zerato", "code": "c2010", "zodiacId": 1 },
  { "name": "Cidd", "code": "c1014", "zodiacId": 1 },
  { "name": "Clarissa", "code": "c1028", "zodiacId": 5 },
  { "name": "Coli", "code": "c1033", "zodiacId": 8 },
  { "name": "Corvus", "code": "c1012", "zodiacId": 4 },
  { "name": "Crescent Moon Rin", "code": "c2054", "zodiacId": 2 },
  { "name": "Crimson Armin", "code": "c2008", "zodiacId": 7 },
  { "name": "Crozet", "code": "c1036", "zodiacId": 4 },
  { "name": "Dingo", "code": "c1021", "zodiacId": 6 },
  { "name": "Dominiel", "code": "c1037", "zodiacId": 2 },
  { "name": "Fighter Maya", "code": "c2032", "zodiacId": 7 },
  { "name": "Free Spirit Tieria", "code": "c3026", "zodiacId": 6 },
  { "name": "Furious", "code": "c1087", "zodiacId": 5 },
  { "name": "General Purrgis", "code": "c2035", "zodiacId": 4 },
  { "name": "Great Chief Khawana", "code": "c2086", "zodiacId": 2 },
  { "name": "Guider Aither", "code": "c2018", "zodiacId": 4 },
  { "name": "Karin", "code": "c1011", "zodiacId": 5 },
  { "name": "Khawana", "code": "c1086", "zodiacId": 12 },
  { "name": "Khawazu", "code": "c1085", "zodiacId": 8 },
  { "name": "Kitty Clarissa", "code": "c2028", "zodiacId": 6 },
  { "name": "Kizuna AI", "code": "c1107", "zodiacId": 4 },
  { "name": "Leo", "code": "c1029", "zodiacId": 10 },
  { "name": "Lots", "code": "c1031", "zodiacId": 3 },
  { "name": "Maya", "code": "c1032", "zodiacId": 1 },
  { "name": "Mercedes", "code": "c1005", "zodiacId": 8 },
  { "name": "Purrgis", "code": "c1035", "zodiacId": 8 },
  { "name": "Rin", "code": "c1054", "zodiacId": 6 },
  { "name": "Roaming Warrior Leo", "code": "c2029", "zodiacId": 3 },
  { "name": "Romann", "code": "c1043", "zodiacId": 3 },
  { "name": "Rose", "code": "c1003", "zodiacId": 7 },
  { "name": "Schuri", "code": "c1020", "zodiacId": 5 },
  { "name": "Serila", "code": "c1040", "zodiacId": 11 },
  { "name": "Shadow Rose", "code": "c2003", "zodiacId": 3 },
  { "name": "Shooting Star Achates", "code": "c2017", "zodiacId": 4 },
  { "name": "Silk", "code": "c1004", "zodiacId": 6 },
  { "name": "Sinful Angelica", "code": "c2062", "zodiacId": 2 },
  { "name": "Surin", "code": "c1065", "zodiacId": 3 },
  { "name": "Tempest Surin", "code": "c2065", "zodiacId": 3 },
  { "name": "Troublemaker Crozet", "code": "c2036", "zodiacId": 12 },
  { "name": "Wanderer Silk", "code": "c2004", "zodiacId": 10 },
  { "name": "Watcher Schuri", "code": "c2020", "zodiacId": 8 },
  { "name": "Zerato", "code": "c1010", "zodiacId": 1 },
  { "name": "Adlay", "code": "c3043", "zodiacId": 9 },
  { "name": "Adventurer Ras", "code": "c5001", "zodiacId": 7 },
  { "name": "Ainos", "code": "c3105", "zodiacId": 9 },
  { "name": "Ains", "code": "c3093", "zodiacId": 7 },
  { "name": "Aither", "code": "c1018", "zodiacId": 7 },
  { "name": "Alexa", "code": "c3012", "zodiacId": 5 },
  { "name": "All-Rounder Wanda", "code": "c4065", "zodiacId": 3 },
  { "name": "Angelic Montmorancy", "code": "c4042", "zodiacId": 12 },
  { "name": "Arowell", "code": "c3004", "zodiacId": 7 },
  { "name": "Azalea", "code": "c3031", "zodiacId": 8 },
  { "name": "Bask", "code": "c3006", "zodiacId": 8 },
  { "name": "Batisse", "code": "c3095", "zodiacId": 2 },
  { "name": "Butcher Corps Inquisitor", "code": "c3001", "zodiacId": 5 },
  { "name": "Captain Rikoris", "code": "c4034", "zodiacId": 7 },
  { "name": "Carmainerose", "code": "c3071", "zodiacId": 11 },
  { "name": "Carrot", "code": "c3051", "zodiacId": 9 },
  { "name": "Celeste", "code": "c3064", "zodiacId": 9 },
  { "name": "Chaos Inquisitor", "code": "c4001", "zodiacId": 5 },
  { "name": "Chaos Sect Axe", "code": "c4025", "zodiacId": 5 },
  { "name": "Church of Ilryos Axe", "code": "c3025", "zodiacId": 5 },
  { "name": "Commander Lorina", "code": "c4035", "zodiacId": 5 },
  { "name": "Doll Maker Pearlhorizon", "code": "c4073", "zodiacId": 2 },
  { "name": "Doris", "code": "c3044", "zodiacId": 4 },
  { "name": "Eaton", "code": "c3094", "zodiacId": 4 },
  { "name": "Elson", "code": "c3054", "zodiacId": 12 },
  { "name": "Enott", "code": "c3022", "zodiacId": 8 },
  { "name": "Falconer Kluri", "code": "c4003", "zodiacId": 1 },
  { "name": "Glenn", "code": "c3103", "zodiacId": 7 },
  { "name": "Gloomyrain", "code": "c3074", "zodiacId": 4 },
  { "name": "Godmother", "code": "c3101", "zodiacId": 3 },
  { "name": "Gunther", "code": "c3024", "zodiacId": 7 },
  { "name": "Hataan", "code": "c3091", "zodiacId": 5 },
  { "name": "Hazel", "code": "c3041", "zodiacId": 11 },
  { "name": "Helga", "code": "c3023", "zodiacId": 9 },
  { "name": "Hurado", "code": "c3055", "zodiacId": 12 },
  { "name": "Ian", "code": "c3102", "zodiacId": 6 },
  { "name": "Jecht", "code": "c3053", "zodiacId": 9 },
  { "name": "Jena", "code": "c3052", "zodiacId": 1 },
  { "name": "Judith", "code": "c3011", "zodiacId": 12 },
  { "name": "Kikirat v2", "code": "c3084", "zodiacId": 10 },
  { "name": "Kiris", "code": "c3063", "zodiacId": 10 },
  { "name": "Kluri", "code": "c3003", "zodiacId": 1 },
  { "name": "Lena", "code": "c3092", "zodiacId": 7 },
  { "name": "Lorina", "code": "c3035", "zodiacId": 5 },
  { "name": "Lucy", "code": "c3113", "zodiacId": 6 },
  { "name": "Magic Scholar Doris", "code": "c4044", "zodiacId": 4 },
  { "name": "Mascot Hazel", "code": "c4041", "zodiacId": 11 },
  { "name": "Mercenary Helga", "code": "c4023", "zodiacId": 9 },
  { "name": "Mirsa", "code": "c3014", "zodiacId": 12 },
  { "name": "Mistychain", "code": "c3072", "zodiacId": 5 },
  { "name": "Montmorancy", "code": "c3042", "zodiacId": 12 },
  { "name": "Mucacha", "code": "c3033", "zodiacId": 9 },
  { "name": "Muse Rima", "code": "c4062", "zodiacId": 11 },
  { "name": "Nemunas", "code": "c3061", "zodiacId": 7 },
  { "name": "Otillie", "code": "c3045", "zodiacId": 2 },
  { "name": "Pearlhorizon", "code": "c3073", "zodiacId": 2 },
  { "name": "Pyllis", "code": "c3005", "zodiacId": 4 },
  { "name": "Ras", "code": "c1001", "zodiacId": 7 },
  { "name": "Requiemroar", "code": "c3075", "zodiacId": 9 },
  { "name": "Researcher Carrot", "code": "c4051", "zodiacId": 9 },
  { "name": "Righteous Thief Roozid", "code": "c4013", "zodiacId": 3 },
  { "name": "Rikoris", "code": "c3034", "zodiacId": 7 },
  { "name": "Rima", "code": "c3062", "zodiacId": 11 },
  { "name": "Roozid", "code": "c3013", "zodiacId": 3 },
  { "name": "Sonia", "code": "c3104", "zodiacId": 12 },
  { "name": "Sven", "code": "c3015", "zodiacId": 8 },
  { "name": "Taranor Guard", "code": "c3032", "zodiacId": 7 },
  { "name": "Taranor Royal Guard", "code": "c3002", "zodiacId": 8 },
  { "name": "Tieria", "code": "c3021", "zodiacId": 1 },
  { "name": "Wanda", "code": "c3065", "zodiacId": 3 },
  { "name": "Zealot Carmainerose", "code": "c4071", "zodiacId": 11 },
  { "code": "c6001", "name": "Angel of Light Angelica", "zodiacId": 2 },
  { "code": "c6002", "name": "Camilla", "zodiacId": 6 },
  { "code": "c6003", "name": "Christy", "zodiacId": 10 },
  { "code": "c6004", "name": "Closer Charles", "zodiacId": 8 },
  { "code": "c6007", "name": "Emilia", "zodiacId": 3 },
  { "code": "c6009", "name": "Helen", "zodiacId": 4 },
  { "code": "c6010", "name": "Ilynav", "zodiacId": 3 },
  { "code": "c6011", "name": "Inferno Khawazu", "zodiacId": 8 },
  { "code": "c6014", "name": "Melany", "zodiacId": 7 },
  { "code": "c6016", "name": "Penelope", "zodiacId": 8 },
  { "code": "c6018", "name": "Ram", "zodiacId": 3 },
  { "code": "c6019", "name": "Rem", "zodiacId": 8 },
  { "code": "c6022", "name": "Straze", "zodiacId": 2 },
  { "code": "c6023", "name": "Summertime Iseria", "zodiacId": 10 }
]

module.exports = heroList;